name: "Generate Next Version Tag"
description: "Determines the next semantic version for an image based on the environment"

inputs:
  image_name:
    description: "Name of the Docker image"
    required: true
  environment:
    description: "The environment the PR is targeting"
    required: true

outputs:
  latest_tag:
    description: "Latest found tag for the image"
    value: ${{ steps.generate-tag.outputs.latest_tag }}
  new_tag:
    description: "New versioned tag to use"
    value: ${{ steps.generate-tag.outputs.new_tag }}

runs:
  using: "composite"
  steps:
    - name: Get Latest Tag
      id: get-latest-tag
      uses: ./.github/workflows/composite_actions/get_latest_tag
      with:
        image_name: ${{ inputs.image_name }}
        environment: ${{ inputs.environment }}

    - name: Generate Version Tag
      id: generate-tag
      uses: actions/github-script@v7
      with:
        script: |
          const imageName = '${{ inputs.image_name }}';
          const environment = '${{ inputs.environment }}';

          async function determineNextVersion(latestTag) {
            console.log(`Processing Latest Tag: ${latestTag}`);

            const versionMatch = latestTag.match(/v(\d+)\.(\d+)\.(\d+)/);
            let major = 0, minor = 0, patch = 0;

            if (versionMatch) {
              major = parseInt(versionMatch[1]);
              minor = parseInt(versionMatch[2]);
              patch = parseInt(versionMatch[3]);
            }

            patch += 1;
            let newVersion = `${imageName}-v${major}.${minor}.${patch}`;

            switch (environment) {
              case "development":
                return `${newVersion}-dev`;
              case "stagging":
                return `${newVersion}-stagging`;
              case "delivery":
                return newVersion;
              default:
                core.setFailed(`Unknown environment '${environment}', expected one of: development, stagging, delivery.`);
            }
          }

          const latestTag = "${{ steps.get-latest-tag.outputs.latest_tag }}";
          const newTag = await determineNextVersion(latestTag);

          core.group("Context Information", () => {
            console.log(`Image: ${imageName}`);
            console.log(`Environment: ${environment}`);
            console.log(`Latest Tag Found: ${latestTag}`);
            console.log(`New Version Generated: ${newTag}`);
          });

          core.setOutput("latest_tag", latestTag);
          core.setOutput("new_tag", newTag);


