name: "Convert Repository Owner to Lowercase"
description: "Outputs the lowercase repository owner name"

outputs:
  repo_owner:
    description: "Lowercased repository owner name"
    value: ${{ steps.lowercased-owner.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Convert Owner Name to Lowercase
      id: lowercased-owner
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          core.group("Context Information", () => {
            console.log(`Repository Owner: ${context.repo.owner}`);
            console.log(`Repository Name: ${context.repo.repo}`);
            console.log(`Repository Owner Lower Cased: ${context.repo.owner.toLowerCase()}`);
          });

          return context.repo.owner.toLowerCase();
