name: Auto Tagging

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch environment'
        required: true
        type: choice
        options:
          - development
          - stagging
          - delivery
  push:
  pull_request:
    branches:
      - dev
      - stagging
      - master
    types:
      - closed

jobs:
  generate-matrix:
    uses: ./.github/workflows/set_matrix.yml

  generate-tags:
    needs: generate-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        IMAGE_DIR: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all tags

      - name: Get Environment
        id: get-environment
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: ./.github/workflows/composite_actions/get_environment
        with:
          branch: ${{ github.event_name == 'push' && github.ref_name || github.base_ref }}

      - name: Generate Next Version
        id: generate-version
        uses: ./.github/workflows/composite_actions/generate_version
        with:
          image_name: ${{ matrix.IMAGE_DIR }}
          environment: ${{ github.event_name == 'workflow_dispatch' && github.inputs.ref || steps.get-environment.outputs.environment }}
        
      - name: Create and Push Tag
        if: ${{ steps.generate-version.outputs.new_tag }} != ''
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag  ${{ steps.generate-version.outputs.new_tag }}
          git push origin  ${{ steps.generate-version.outputs.new_tag }}