name: Set Matrix
on:
  workflow_call:
    outputs:
      matrix:
        description: "The generated matrix"
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read-matrix.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # - run: npm ci
      - run: |
          npm install \
            fs \
            js-yaml

      - id: read-matrix 
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const matrix = yaml.load(fs.readFileSync('.github/workflows/resources/matrix.yml', 'utf8'));
            const result = JSON.stringify(matrix.images)
            console.log(result);
            return result
          